### ISSUE TITLE
Name conflicts with existing library

### ISSUE THREAD

**Issue by robertmclaws** [Mewgrammer/BlazorEssentials#3]
Hello! My name is Robert McLaws, and I'm the maker of the BlazorEssentials library. You've built some really cool stuff here, thanks for putting it out there! Would it be possible to chat at some point about the name? I normally wouldn't mind, except to an outside programmer, it would appear these libraries are parts of the same product, and they aren't.

![image](https://user-images.githubusercontent.com/1657085/59567579-a2c90a80-903d-11e9-8158-68f349a38b87.png)

If you're open to it, I would love to brainstorm with you and see if we could come up with a creative solution. Looking forward to it! :)

**Comment by Mewgrammer** [comment]
Hello Rober,

I just renamed the repo and unlisted the packages, sorry for the inconvenience.

**Comment by robertmclaws** [comment]
No worries, I was going to suggest that we could collaborate and see if there is overlap between the libraries, but this works too. You're awesome, keep up the great work! :)
